### ISSUE TITLE
Add .notdef

### ISSUE THREAD

**Issue by pathumego** [mooniak/yaldevi-fonts#38]
@kosalaya I added notdef glyph to all of SNB files with last commit please copy and paste the same glyphs into tamil files and sinhala. CHange it to fit the wieghts

**Comment by paarandika** [comment]
Adding .notdef to single lang is enough

**Comment by pathumego** [comment]
Yes, But if someone wants to spit out a font out of just Sinhala or Tamil they will have to copy and paste .notdef  No harm in having it in all files

**Comment by davelab6** [comment]
Is this done?

**Comment by pathumego** [comment]
Completed
