### ISSUE TITLE
Curious case of changing path direction

### ISSUE THREAD

**Issue by pathumego** [mooniak/yaldevi-fonts#46]
Ok, we have only one issue left for v.1.

<img width="1123" alt="screen shot 2016-01-24 at 12 13 45 pm" src="https://cloud.githubusercontent.com/assets/6846609/12536190/8171b82e-c295-11e5-90f0-6e03c2ea4c7e.png">

These eroors are noramally caused by opposite path directions.But the sources are correct. The directions of the MatraI.alt set are changind during the build. I tracked the stages and It is intact till the combining masters. I think this is happening when overlap removal process.

When I open the built font files FontForge shows this error.
<img width="665" alt="screen shot 2016-01-24 at 12 34 44 pm" src="https://cloud.githubusercontent.com/assets/6846609/12536227/41aafb72-c297-11e5-8a19-a2f4724a1581.png">

But not Glyphs App. It seems like Glyphs is showing the start point also differently. And none of these errors are visible in the browser.
<img width="646" alt="screen shot 2016-01-24 at 12 33 35 pm" src="https://cloud.githubusercontent.com/assets/6846609/12536237/5554f0b0-c297-11e5-8f4c-a1f4e36ac694.png">

@paarandika

**Comment by paarandika** [comment]
Regular in MS Word
![ayanna](https://cloud.githubusercontent.com/assets/6725097/12537015/ec34d87c-c2da-11e5-9438-6f016c4cfd95.PNG)

**Comment by davelab6** [comment]
Can this be closed?

**Comment by pathumego** [comment]
I just changed the direction in the source file to undo the direction error in build. @paarandika has to examine and fix the build.

**Comment by pathumego** [comment]
This is fixed
