### ISSUE TITLE
Dual Script Family Names

### ISSUE THREAD

**Issue by davelab6** [mooniak/yaldevi-fonts#47]
To serve Ayanna Narrow as web fonts, I need to have it as two Dual Script families, Latin + Sinhala and Latin + Tamil, unless we are 100% sure that there are no overlapping Unicode values.

**Comment by davelab6** [comment]
Potentially this should be done as a shell/python script that uses `pyftsubset` and a fontbakery/`fonttools` family renaming script to split the fonts as part of the release script

**Comment by pathumego** [comment]
@davelab6 what do you exactly mean by overlapping values. Shared unicode codepoints in both Sinhala and Tamil blocks? According to http://unicode.org/charts/PDF/U0D80.pdf and http://unicode.org/charts/PDF/U0B80.pdf there is no overlapping. zwj, zwnj is not a problem in my understanding of the issue.

**Comment by davelab6** [comment]
Not sure, and I don't have time to test this well, I suggest shipping "Ayanna Narrow" with latin + sinhala, and "Ayanna Narrow Madurai" with latin + tamil

**Comment by pathumego** [comment]
Ok @paarandika  :) coming your way.

**Comment by pathumego** [comment]
Ok Family names, @DenzelRajitha @kosalaya @paarandika  Lets do `Ayanna` for Sin + Latin and `Ayanna Yalpanam` for Tam+Latin?

**Comment by kosalaya** [comment]
fine by me

**Comment by davelab6** [comment]
SGTM

**Comment by pathumego** [comment]
@davelab6 finally done :)
