### ISSUE TITLE
Release TTFs

### ISSUE THREAD

**Issue by davelab6** [mooniak/yaldevi-fonts#52]
To onboard the family I need TTF files, but these are not in the 1.000 release or gh-pages branch

**Comment by pathumego** [comment]
@davelab6 What are the best tools to generate ttf's? 
OTF>fontforge>TTF>ttfautohint>

cc @paarandika We have to add this ttf+ webfont build thing to make_release script, And pyftsubset thig to subset if wanted.

**Comment by davelab6** [comment]
No, making an OTF then converting to TTF bloats the filesize :(

**Comment by davelab6** [comment]
https://github.com/mooniak/ayanna-font/tree/master/sources has many files; which are actually used to build?

**Comment by pathumego** [comment]
Ufo's are combined and built during the process, So combined masters are not included in the repo.

**Comment by davelab6** [comment]
Sure, which files are actually used to build?

**Comment by davelab6** [comment]
I see in https://github.com/mooniak/ayanna-font/blob/master/scripts/builder.sh that SFDs are the 'real' sources

**Comment by davelab6** [comment]
So, why are the intermediate UFOs checked into the repo, if they are just temporary build files? :)

**Comment by pathumego** [comment]
yes, kept the sfd generated ufo's considering collaboration. Since Sol's files are also coming in as UFO's.

**Comment by davelab6** [comment]
Any luck?

**Comment by paarandika** [comment]
I'm developing a script. Most probably it will work :)

**Comment by paarandika** [comment]
Added a crude script to build separate ttf for Sinhala and Tamil

**Comment by davelab6** [comment]
Awesome! I'll take a look next week

**Comment by pathumego** [comment]
We have problems with the files. @paarandika posted me the generated files. 
- [ ] Some glyphs are flipped
- [ ] Overlap is not removed (fontconvert can do --remove overlap)

I am testing the files now and will post a complete review soon.

**Comment by paarandika** [comment]
Which glyphs are flipped?
I did checkoutlines using same script as in Hindkit. It should remove overlaps..

**Comment by pathumego** [comment]
I'll post in detail, open the ttfs and see

On Sat, Mar 5, 2016, 2:27 PM Ayantha Randika <notifications@github.com>
wrote:

> Which glyphs are flipped?
> I did checkoutlines using same script as in Hindkit. It should remove
> overlaps..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mooniak/ayanna-font/issues/52#issuecomment-192641864>.
>
-- 

෴ ජය! ෴
පැතුම් එගොඩවත්ත
Pathum Egodawatta
pathum@mooniak.com

**Comment by paarandika** [comment]
Could not find any issues

**Comment by pathumego** [comment]
Yep, it was my mistake. It works,but there is a problem with `/space`. It is not interpolating it seems. I have to check again with against otf's. Lets keep this open till @davelab6 take a look at this. And @paarandika we have few things to clean up
- [ ] need separate family names for ttf's Sin+ Latin  and Tamil+ Latin (#47)
- [ ] Move `ttf-build` into `./build/ttf`
- [ ] Move `gf-build` scripts into `./scripts` folder. So its clean.
- [ ] Update readme with info on build process and how its done. A simple description is fine.

**Comment by paarandika** [comment]
One and four I will do and I will check "space" as well.
For three and four Nope

**Comment by davelab6** [comment]
1 + 4 vs 3 + 4, I'm confused :)

**Comment by paarandika** [comment]
Ooops!
One and four I will do and I will check "space" as well.
For two and three Nope

**Comment by davelab6** [comment]
Cool. BTW https://github.com/rosettatype/yrsa-rasa may be helpful

**Comment by pathumego** [comment]
@davelab6 The ttf's are like this, DO you think there is a better way to do this?
<img width="1745" alt="screen shot 2016-03-15 at 12 03 26 pm" src="https://cloud.githubusercontent.com/assets/6846609/13777124/04ad1eb2-eaa6-11e5-823c-3331b131de87.png">

**Comment by pathumego** [comment]
@paarandika among other things, I think its better if we can just build the combined ttf's and then split with pyftsubset. Instead of maintaining multiple feature files

**Comment by davelab6** [comment]
You could try using fontcrunch to remove the excess TT points.

Do not use Glyphs to inspect TTFs though, it re-converts TT outlines to PS.

**Comment by pathumego** [comment]
Yeah, So excess points are added during conversion to TT outlines? @paarandika  So we only have to figure out what's happening with glyphs with changed directions.

**Comment by pathumego** [comment]
These glyphs have problems in curves, I think they are all using componants and FF complier mess up that. 
`tml_Debit, tml_Ee, tml_Four, tml_KSsU, tml_KSsUu, tml_KSsa, tml_Month, tml_NUu, tml_Nine, tml_NnUu, tml_NnnUu, tml_NyU, tml_NyUu, tml_TUu, `

`si_DdR.halant, si_DdRI, si_DdRIi, si_FR.halant, si_FRI, si_FRIi, si_GR.halant, si_GRI, si_GRIi, si_GhR.halant, si_GhRI, si_GhRIi, si_HR.halant, si_HRI, si_HRIi, si_JhR.halant, si_JhRI, si_JhRIi, si_KhR.halant, si_KhRI, si_KhRIi, si_MR.halant, si_MRI, si_MRIi, `

**Comment by pathumego** [comment]
Otf's are perfectly fine. I thik we could use Unlink Reference in FF python to fix this on export.

**Comment by davelab6** [comment]
Won't that bloat the filesize?

**Comment by pathumego** [comment]
Yeah, waiting for Randika to look at the files.
