### ISSUE TITLE
Renaming source files?

### ISSUE THREAD

**Issue by pathumego** [mooniak/yaldevi-fonts#58]
We renamed the family but the source files are still named as `Ayanna*` SHould we keep that as it is or change to new name? Will loose the git history attached to files if we rename?

**Comment by davelab6** [comment]
You can use

    git mv

And it will retain `git blame` history etc

**Comment by davelab6** [comment]
Also the rename was from `Ayanna Narrow` to `Yaldevi` - do you plan to ever make wider styles? If so, then the width should be in the family name

**Comment by pathumego** [comment]
No It was from `Ayanna` to `Yaldevi`. We decided to consider this as the regular width style. A wider style could by `Yaldevi Wide`
