### ISSUE TITLE
[yaldevi-tamil] Misplaced Glyph Slots 

### ISSUE THREAD

**Issue by enathu** [mooniak/yaldevi-fonts#65]
@pathumego @paarandika https://github.com/google/fonts/pull/670#issuecomment-281096017

Cheers. :)

**Comment by pathumego** [comment]
@enathu Thanks

**Comment by pathumego** [comment]
Fixed --> https://github.com/mooniak/yaldevi-fonts/releases/tag/1.030 
Thanks @enathu
