### ISSUE TITLE
space and nbspace do not share the same advance width

### ISSUE THREAD

**Issue by m4rc1e** [mooniak/yaldevi-fonts#66]
Hello,

Before I can pr this to GF, I'd like the nbspace and space to share the same advance width. 

**Output from FB for YaldeviColombo-Bold.ttf:
```
ERROR    space 250 nbsp 190: Nbsp advanceWidth needs to be fixed to 250
```

This error is in both the Regular and Bold weights. I'd check all the weights in both families.

**Comment by pathumego** [comment]
Thanks Marc! Looking into this

**Comment by davelab6** [comment]
@pathumego ping
