### ISSUE TITLE
Font weights are not display in MS-Word and LibreOffice 

### ISSUE THREAD

**Issue by edesigns-LK** [mooniak/yaldevi-fonts#68]
### Font family name (weights) are not display in MS-Word and LibreOffice.  (same for Abhaya Libre too)

![Yaldevi_00](https://user-images.githubusercontent.com/52587663/60749774-94c33580-9fbc-11e9-9aaa-c2d849da7733.png)

**Comment by pathumego** [comment]
@edesigns-LK Can you test with these files?
[YaldeviTEST.zip](https://github.com/mooniak/yaldevi-fonts/files/6554072/YaldeviTEST.zip)

**Comment by pathumego** [comment]
Fixed
